server:
  port: 8081
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /subject

spring:
  config:
    activate:
      on-profile: subject
  application:
    name: mssubject

logging:
  level:
    root: info
    web: info
    it.cgmconsulting.msword: info

eureka:
  client:
    service-url:
      default-zone: localhost:8761/eureka

app:
  name: subject
  items: sub1,sub2,sub3,sub4,sub5

---

server:
  port: 8082
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /verb

spring:
  config:
    activate:
      on-profile: verb
  application:
    name: msverb

logging:
  level:
    root: info
    web: info
    it.cgmconsulting.msword: info

eureka:
  client:
    service-url:
      default-zone: localhost:8761/eureka

app:
  name: verb
  items: verb1,verb2,verb3,verb4,verb5
---

server:
  port: 8083
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /object

spring:
  config:
    activate:
      on-profile: object
  application:
    name: msobject

logging:
  level:
    root: info
    web: info
    it.cgmconsulting.msword: info

eureka:
  client:
    service-url:
      default-zone: localhost:8761/eureka

app:
  name: object
  items: obj1,obj2,obj3,obj4,obj5
